class NeuralNetwork{
  constructor(){this.learningRate=.35;this.reset()}
  reset(){this.layers=[2,8,6,1];this.weights=[];this.biases=[];for(let l=0;l<this.layers.length-1;l++){this.weights.push(this.matrix(this.layers[l+1],this.layers[l]));this.biases.push(Array(this.layers[l+1]).fill(0).map(()=>this.rand()))}}
  rand(){return (Math.random()*2-1)*Math.sqrt(2/8)}
  matrix(rows,cols){return Array.from({length:rows},()=>Array.from({length:cols},()=>this.rand()))}
  sigmoid(x){return 1/(1+Math.exp(-Math.max(-60,Math.min(60,x))))}
  forward(input,trace=false){let a=input.slice(),acts=[a];for(let l=0;l<this.weights.length;l++){a=this.weights[l].map((row,j)=>this.sigmoid(this.biases[l][j]+row.reduce((s,w,i)=>s+w*a[i],0)));acts.push(a)}return trace?acts:{output:a[0],hidden:a}}
  train(input,target){const a=this.forward(input,true),d=Array(this.weights.length);let last=a[a.length-1];d[d.length-1]=last.map((v,j)=>(target[j]??target-v)*v*(1-v));
    for(let l=this.weights.length-2;l>=0;l--){d[l]=a[l+1].map((v,j)=>v*(1-v)*this.weights[l+1].reduce((s,row,k)=>s+row[j]*d[l+1][k],0))}
    for(let l=0;l<this.weights.length;l++){for(let j=0;j<this.weights[l].length;j++){for(let i=0;i<this.weights[l][j].length;i++)this.weights[l][j][i]+=this.learningRate*d[l][j]*a[l][i];this.biases[l][j]+=this.learningRate*d[l][j]}}
    return (target-last[0])**2
  }
  predict(input){return this.forward(input).output}
  serialize(){return{layers:this.layers,weights:this.weights,biases:this.biases,learningRate:this.learningRate}}
  restore(d){if(!d?.weights||!d?.biases||!Array.isArray(d.layers))throw Error('Estado inválido');this.layers=d.layers;this.weights=d.weights;this.biases=d.biases;this.learningRate=Number(d.learningRate)||.35}
}

const data=[[[0,0],[0]],[[0,1],[1]],[[1,0],[1]],[[1,1],[0]]],$=id=>document.getElementById(id);
const SUPABASE_URL='https://otdfvaufiqwlwmaqsljs.supabase.co',SUPABASE_KEY='sb_publishable_f0BM6a9YHx-jT1Rn1f9h6A_hj1BQ-yO',STATE='__NEURAL_NETWORK_STATE_V3__',MEM='neural2d_memory_v2';
const brain=new NeuralNetwork();let db=null,memory=[],epoch=0,loss=1,trained=false,savePromise=null,learningEvents=0;
function localLoad(){try{return JSON.parse(localStorage.getItem(MEM)||'[]')}catch{return[]}}
function localSave(){try{localStorage.setItem(MEM,JSON.stringify(memory.slice(-500)))}catch{}}
function status(t,e=false){if($('dbState')){$('dbState').textContent=t;$('dbState').classList.toggle('error',e)}if($('chatState'))$('chatState').textContent=t}
function errText(e){const m=String(e?.message||e?.details||e||'error');console.error('[Supabase]',e);if(/Invalid API key|invalid api key/i.test(m))return'API key de Supabase inválida';if(/42P01|relation .*neural_memory.*does not exist/i.test(m))return'Tabla neural_memory no existe';if(/42501|row-level security|permission denied|JWT|401|403/i.test(m))return'Permisos RLS de Supabase';if(/Failed to fetch|NetworkError|CORS|fetch/i.test(m))return'No se puede conectar a Supabase';return'Supabase: '+m.slice(0,80)}
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(Error('No se pudo cargar '+src));document.head.appendChild(s)})}
async function initDb(){if(!window.supabase?.createClient){for(const src of ['https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2','https://unpkg.com/@supabase/supabase-js@2/dist/umd/supabase.min.js']){try{await loadScript(src);if(window.supabase?.createClient)break}catch(e){}}}if(!window.supabase?.createClient){status('Supabase JS no disponible',true);return false}try{db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return true}catch(e){status(errText(e),true);return false}}
async function dbCall(p,ms=10000){return Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(Error('Tiempo de espera agotado')),ms))])}
async function load(){memory=localLoad();update();status('conectando…');if(!await initDb()){update();return}try{const{data:rows,error}=await dbCall(db.from('neural_memory').select('question,answer,created_at').order('created_at',{ascending:false}).limit(500));if(error)throw error;const sr=rows?.find(r=>r.question===STATE);memory=(rows||[]).filter(r=>r.question!==STATE);if(sr)try{const s=JSON.parse(sr.answer);brain.restore(s.network);epoch=Number(s.epoch)||0;loss=Number(s.loss)||1;trained=!!s.trained;learningEvents=Number(s.learningEvents)||0}catch(e){console.warn('Estado:',e)}localSave();status(`base de datos · ${memory.length} recuerdos`);update()}catch(e){status(errText(e),true);update()}}
async function saveState(){if(!db||savePromise)return;const payload=JSON.stringify({network:brain.serialize(),epoch,loss,trained,learningEvents,updatedAt:new Date().toISOString()});savePromise=(async()=>{try{const{data:old,error:r}=await dbCall(db.from('neural_memory').select('question').eq('question',STATE).limit(1));if(r)throw r;const q=old?.length?db.from('neural_memory').update({answer:payload}).eq('question',STATE):db.from('neural_memory').insert({question:STATE,answer:payload});const{error}=await dbCall(q);if(error)throw error;status(`base de datos · ${memory.length} recuerdos`)}catch(e){console.warn('Guardado:',e);localSave();status(errText(e),true)}finally{savePromise=null}})()}
function queueSaveState(){clearTimeout(queueSaveState.timer);queueSaveState.timer=setTimeout(saveState,500)}
async function saveMemory(q,a){memory.unshift({question:q,answer:a});memory=memory.slice(0,500);localSave();if(!db)return;try{const{error}=await dbCall(db.from('neural_memory').insert({question:q.slice(0,300),answer:a.slice(0,600)}));if(error)throw error;status(`base de datos · ${memory.length} recuerdos`)}catch(e){status(errText(e),true)}}
function norm(s){return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9ñ?¿! ]/g,'').replace(/\s+/g,' ').trim()}
function learned(q){const n=norm(q);return memory.find(v=>norm(v.question)===n)?.answer||null}
function vector(s){const n=norm(s),v=Array(2).fill(0);let a=0,b=0;for(const ch of n){a=(a+ch.charCodeAt(0))%997;b=(b+ch.charCodeAt(0)*((a%13)+1))%991}return[a/997,b/991]}
function learnFromChat(q){const v=vector(q),target=q.length%2?.9:.1;let e=0;for(let i=0;i<8;i++)e+=brain.train(v,[target]);loss=e/8;epoch+=8;learningEvents++;trained=true;queueSaveState();update()}
function knowledge(){return{architecture:brain.layers.join(' → '),training:'XOR + aprendizaje continuo de entradas del chat',epochs:epoch,error:loss,trained,memories:memory.length,learningEvents,weights:brain.serialize()}}
function learnedSummary(){const k=knowledge();return k.trained?`Mi estado actual viene de lo que tengo guardado. Estoy usando una red ${k.architecture}, entrenada con XOR y ajustada con entradas del chat. Llevo ${k.epochs.toLocaleString()} épocas, mi error registrado es ${k.error.toFixed(4)} y he procesado ${k.learningEvents.toLocaleString()} experiencias. Tengo ${k.memories} recuerdos guardados y mis pesos actuales están persistidos.`:'Todavía estoy inicializando mi aprendizaje.'}
function nodePos(l,i,w,h){const counts=brain.layers,x=w*(l/(counts.length-1));const c=counts[l],gap=Math.min(68,h*.13);return{x,y:h/2+(i-(c-1)/2)*gap}}
function draw(){const c=$('networkCanvas');if(!c)return;const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(320,r.width),h=Math.max(320,r.height);c.width=w*d;c.height=h*d;const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.fillStyle='#090909';x.fillRect(0,0,w,h);const p=brain.layers.map((n,l)=>Array.from({length:n},(_,i)=>nodePos(l,i,w,h)));x.textAlign='center';x.font='10px system-ui';p.forEach((layer,l)=>{x.fillStyle='#666';x.fillText(l===0?'ENTRADA':l===p.length-1?'SALIDA':`OCULTA ${l}`,layer[0].x,Math.max(18,layer[0].y-80))});for(let l=0;l<p.length-1;l++)for(let a=0;a<p[l].length;a++)for(let b=0;b<p[l+1].length;b++){const wt=brain.weights[l][b][a];x.beginPath();x.moveTo(p[l][a].x,p[l][a].y);x.lineTo(p[l+1][b].x,p[l+1][b].y);x.lineWidth=1+Math.min(4,Math.abs(wt)*2);x.strokeStyle=wt>=0?'rgba(210,210,210,.42)':'rgba(100,100,100,.42)';x.stroke()}p.forEach((layer,l)=>layer.forEach((v,i)=>{const z=l===0||l===p.length-1?25:17;x.beginPath();x.arc(v.x,v.y,z,0,Math.PI*2);x.fillStyle='#222';x.fill();x.lineWidth=2;x.strokeStyle='#888';x.stroke();x.fillStyle='#eee';x.font='600 10px system-ui';x.fillText(l===0?`x${i+1}`:l===p.length-1?'y':`h${l}.${i+1}`,v.x,v.y+3)}));x.fillStyle='#555';x.font='11px system-ui';x.fillText(trained?`Aprendida · época ${epoch.toLocaleString()} · experiencias ${learningEvents}`:'Lista para aprender',w/2,h-15)}
function update(){$('epoch').textContent=epoch.toLocaleString();$('loss').textContent=loss.toFixed(4);$('prediction').textContent=brain.predict([0,1]).toFixed(3);$('memoryCount').textContent=memory.length;if($('architecture'))$('architecture').textContent=brain.layers.join(' · ');if($('learningEvents'))$('learningEvents').textContent=learningEvents.toLocaleString();$('result').textContent=trained?'Red entrenada y guardada':'La red todavía está inicializándose';$('infoText').textContent=trained?'El lienzo muestra pesos, capas y estado persistente actuales. Cada mensaje nuevo produce una pequeña actualización del modelo.':'Entrena la red para comenzar a modificar sus pesos.';draw()}
async function train(){const b=$('train');if(b.disabled)return;b.disabled=true;$('reset').disabled=true;$('state').textContent='Entrenando red profunda...';try{for(let n=0;n<100;n++){let e=0;for(let i=0;i<8;i++)for(const[d,y]of data)e+=brain.train(d,y);loss=e/32;epoch++;}trained=true;learningEvents++;update();await new Promise(r=>setTimeout(r,0));}queueSaveState();$('state').textContent='Entrenada y guardada'}catch(e){console.error(e);$('state').textContent='Error al entrenar'}finally{b.disabled=false;$('reset').disabled=false}}
function reply(t){if(!trained)return'Primero necesito entrenarme. 🧠';const n=norm(t);if(n.includes('que aprendiste')||n.includes('que aprendistes')||n.includes('que has aprendido')||n.includes('que sabes'))return learnedSummary();if(n.includes('hola'))return'Hola. Estoy activa y conservando lo aprendido.';if(n.includes('quien eres'))return`Soy una red neuronal artificial ${knowledge().architecture}, con aprendizaje continuo.`;const hit=learned(t);return hit||'No tengo una respuesta almacenada para eso todavía, pero lo registraré y ajustaré mis pesos con esta entrada.'}
function add(t,type){const m=document.createElement('div');m.className=`message ${type==='user'?'userMessage':'neuronMessage'}`;m.textContent=t;$('messages').appendChild(m);$('messages').scrollTop=$('messages').scrollHeight}
$('train').addEventListener('click',train);$('reset').addEventListener('click',()=>{brain.reset();epoch=0;loss=1;trained=false;learningEvents=0;memory=[];localSave();update();$('state').textContent='Modelo reiniciado';queueSaveState()});$('chatForm').addEventListener('submit',e=>{e.preventDefault();const i=$('chatInput'),q=i.value.trim();if(!q)return;add(q,'user');i.value='';const a=reply(q);add(a,'neuron');saveMemory(q,a);learnFromChat(q)});for(const b of document.querySelectorAll('[data-prompt]'))b.addEventListener('click',()=>{$('chatInput').value=b.dataset.prompt;$('chatInput').focus()});$('networkCanvas').addEventListener('click',e=>{const c=$('networkCanvas'),r=c.getBoundingClientRect(),w=r.width,h=r.height;for(let l=0;l<brain.layers.length;l++)for(let i=0;i<brain.layers[l];i++){const p=nodePos(l,i,w,h);if(Math.hypot(e.clientX-r.left-p.x,e.clientY-r.top-p.y)<30){ $('nodeInfo').textContent=`${l===0?`x${i+1}`:l===brain.layers.length-1?'y':`h${l}.${i+1}`} · capa ${l+1} · pesos ${brain.weights[l]?.[i]?.length||0}`;return}}});window.addEventListener('resize',draw);update();load();