/* RedNeuronal v5 */
'use strict';
const $=id=>document.getElementById(id);
const SUPABASE_URL='https://otdfvaufiqwlwmaqsljs.supabase.co';
const SUPABASE_KEY='sb_publishable_f0BM6a9YHx-jT1Rn1f9h6A_hj1BQ-yO';
const STATE_KEY='__NEURAL_NETWORK_STATE_V5__';
const LOCAL_MEMORY_KEY='neural2d_memory_v4';

class NeuralNetwork{
 constructor(layers=[2,12,8,1]){this.layers=layers.slice();this.learningRate=.12;this.reset()}
 reset(){this.weights=[];this.biases=[];for(let l=0;l<this.layers.length-1;l++){const input=this.layers[l],output=this.layers[l+1],scale=Math.sqrt(2/input);this.weights.push(Array.from({length:output},()=>Array.from({length:input},()=>((Math.random()*2-1)*scale))));this.biases.push(Array(output).fill(0))}}
 sigmoid(x){const z=Math.max(-40,Math.min(40,x));return 1/(1+Math.exp(-z))}
 forward(input,trace=false){let a=input.map(Number),acts=[a.slice()];for(let l=0;l<this.weights.length;l++){const next=this.weights[l].map((row,j)=>{let sum=this.biases[l][j];for(let i=0;i<row.length;i++)sum+=row[i]*a[i];return this.sigmoid(sum)});a=next;acts.push(a.slice())}return trace?acts:a[0]}
 train(input,target){const acts=this.forward(input,true),targetValue=Array.isArray(target)?Number(target[0]):Number(target),last=acts.length-1,deltas=Array.from({length:this.weights.length},()=>[]);deltas[last-1]=acts[last].map(v=>(targetValue-v)*v*(1-v));for(let l=this.weights.length-2;l>=0;l--){deltas[l]=acts[l+1].map((v,j)=>{let error=0;for(let k=0;k<this.weights[l+1].length;k++)error+=this.weights[l+1][k][j]*deltas[l+1][k];return error*v*(1-v)})}for(let l=0;l<this.weights.length;l++)for(let j=0;j<this.weights[l].length;j++){for(let i=0;i<this.weights[l][j].length;i++)this.weights[l][j][i]+=this.learningRate*deltas[l][j]*acts[l][i];this.biases[l][j]+=this.learningRate*deltas[l][j]}return(targetValue-acts[last][0])**2}
 predict(input){return this.forward(input)}
 serialize(){return{layers:this.layers,weights:this.weights,biases:this.biases,learningRate:this.learningRate}}
 restore(s){if(!s||!Array.isArray(s.layers)||!Array.isArray(s.weights)||!Array.isArray(s.biases))throw Error('Estado de red inválido');this.layers=s.layers.map(Number);this.weights=s.weights;this.biases=s.biases;this.learningRate=Number(s.learningRate)||.12}
}

const XOR=[{input:[0,0],target:[0]},{input:[0,1],target:[1]},{input:[1,0],target:[1]},{input:[1,1],target:[0]}];
const brain=new NeuralNetwork();let db=null,memory=[],epoch=0,loss=1,trained=false,learningEvents=0,isTraining=false,saveTimer=null;

function normalize(text){return String(text??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9ñ ]/g,' ').replace(/\s+/g,' ').trim()}
function words(text){return new Set(normalize(text).split(' ').filter(w=>w.length>1))}
function similarity(a,b){const A=words(a),B=words(b);if(!A.size||!B.size)return 0;let common=0;for(const w of A)if(B.has(w))common++;return common/(A.size+B.size-common)}
function findMemory(query){let best=null,score=0;for(const item of memory){const s=similarity(query,item.question);if(s>score){score=s;best=item}}return score>=.45?best:null}
function loadLocal(){try{const v=JSON.parse(localStorage.getItem(LOCAL_MEMORY_KEY)||'[]');return Array.isArray(v)?v.slice(0,500):[]}catch{return[]}}
function saveLocal(){try{localStorage.setItem(LOCAL_MEMORY_KEY,JSON.stringify(memory.slice(0,500)))}catch{}}
function setStatus(text,error=false){if($('dbState')){$('dbState').textContent=text;$('dbState').classList.toggle('error',error)}if($('chatState'))$('chatState').textContent=text}
function update(){if($('epoch'))$('epoch').textContent=epoch.toLocaleString();if($('loss'))$('loss').textContent=Number(loss).toFixed(4);if($('prediction'))$('prediction').textContent=brain.predict([0,1]).toFixed(3);if($('memoryCount'))$('memoryCount').textContent=memory.length.toLocaleString();if($('learningEvents'))$('learningEvents').textContent=learningEvents.toLocaleString();if($('architecture'))$('architecture').textContent=brain.layers.join(' · ');if($('result'))$('result').textContent=trained?'Red entrenada y lista para responder':'Pulsa «Entrenar red» para comenzar';if($('infoText'))$('infoText').textContent=trained?`Red ${brain.layers.join(' → ')} · memoria semántica · ${learningEvents.toLocaleString()} experiencias.`:'La red aprende XOR y puede guardar asociaciones de pregunta y respuesta.';draw()}
async function timeout(p,ms=8000){return Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(Error('Tiempo de espera agotado')),ms))])}
async function initDb(){setStatus('conectando base de datos…');if(!window.supabase?.createClient){setStatus('modo local · Supabase no disponible',true);return false}try{db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});return true}catch(e){console.error(e);setStatus('error creando conexión',true);return false}}
async function load(){memory=loadLocal();update();if(!await initDb())return;try{const r=await timeout(db.from('neural_memory').select('question,answer,created_at').order('created_at',{ascending:false}).limit(500));if(r.error)throw r.error;const rows=r.data||[],stateRow=rows.find(x=>x.question===STATE_KEY);const remote=rows.filter(x=>x.question!==STATE_KEY);if(remote.length)memory=remote;if(stateRow){try{const state=JSON.parse(stateRow.answer);brain.restore(state.network);epoch=Number(state.epoch)||0;loss=Number(state.loss)||1;trained=Boolean(state.trained);learningEvents=Number(state.learningEvents)||0}catch(e){console.warn('Estado incompatible',e)}}saveLocal();setStatus(`base de datos conectada · ${memory.length} recuerdos`);update()}catch(e){console.error('Supabase:',e);setStatus('modo local · no se pudo leer Supabase',true);update()}}
async function saveState(){if(!db)return;const payload=JSON.stringify({network:brain.serialize(),epoch,loss,trained,learningEvents,updatedAt:new Date().toISOString()});try{const old=await timeout(db.from('neural_memory').select('question').eq('question',STATE_KEY).limit(1));if(old.error)throw old.error;const op=old.data?.length?db.from('neural_memory').update({answer:payload}).eq('question',STATE_KEY):db.from('neural_memory').insert({question:STATE_KEY,answer:payload});const r=await timeout(op);if(r.error)throw r.error}catch(e){console.warn('No se pudo guardar estado',e)}}
function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(saveState,500)}
async function saveMemory(question,answer){const n=normalize(question),old=memory.find(x=>normalize(x.question)===n);if(old)old.answer=answer;else memory.unshift({question,answer,created_at:new Date().toISOString()});memory=memory.slice(0,500);saveLocal();if(!db)return;try{const r=await timeout(db.from('neural_memory').insert({question:question.slice(0,300),answer:answer.slice(0,600)}));if(r.error)throw r.error;setStatus(`base de datos conectada · ${memory.length} recuerdos`)}catch(e){console.warn('No se pudo guardar recuerdo',e)}}
function trainEpoch(){let total=0;const batch=XOR.slice().sort(()=>Math.random()-.5);for(const s of batch)total+=brain.train(s.input,s.target);return total/XOR.length}
async function train(){if(isTraining)return;isTraining=true;const b=$('train');if(b)b.disabled=true;if($('reset'))$('reset').disabled=true;if($('state'))$('state').textContent='Entrenando…';try{for(let i=0;i<1200;i++){loss=trainEpoch();epoch++;if(i%50===0){update();await new Promise(requestAnimationFrame)}}loss=XOR.reduce((s,x)=>s+(x.target[0]-brain.predict(x.input))**2,0)/XOR.length;trained=true;learningEvents++;update();queueSave();if($('state'))$('state').textContent=`Entrenada · error ${loss.toFixed(4)}`}catch(e){console.error('Entrenamiento:',e);if($('state'))$('state').textContent='Error: '+(e.message||'entrenamiento fallido')}finally{isTraining=false;if(b)b.disabled=false;if($('reset'))$('reset').disabled=false}}
function teach(text){const m=text.match(/^\s*(?:aprende|aprender)\s*[:\-]\s*(.+?)\s*(?:=>|->|=)\s*(.+)\s*$/i);if(!m)return null;const q=m[1].trim(),a=m[2].trim();memory.unshift({question:q,answer:a,created_at:new Date().toISOString()});memory=memory.slice(0,500);learningEvents++;saveLocal();saveMemory(q,a);queueSave();return`Aprendido. Guardé una respuesta para «${q}». 🧠`}
function learnInput(text){const n=normalize(text),count=words(n).size;if(!n)return;const target=Math.min(.9,Math.max(.1,(count%9+1)/10)),input=[Math.min(.99,n.length/300),Math.min(.99,count/30)];let e=0;for(let i=0;i<8;i++)e+=brain.train(input,[target]);loss=e/8;epoch+=8;learningEvents++;trained=true;queueSave()}
function summary(){return`He aprendido patrones con una red ${brain.layers.join(' → ')}. Llevo ${epoch.toLocaleString()} épocas, error ${loss.toFixed(4)}, ${learningEvents.toLocaleString()} experiencias y ${memory.length.toLocaleString()} recuerdos.`}
function answer(text){const n=normalize(text),taught=teach(text);if(taught)return taught;if(/^(hola|holi|hey|buenas|hello)$/.test(n))return'Hola. 🧠 Estoy activa y lista para trabajar con mi memoria.';if(n.includes('que aprendiste')||n.includes('que has aprendido')||n.includes('que sabes'))return summary();if(n.includes('quien eres')||n.includes('que eres'))return`Soy una red neuronal artificial ${brain.layers.join(' → ')} con memoria persistente.`;if(n.includes('que es una red neuronal'))return'Una red neuronal es un modelo matemático formado por capas conectadas que ajusta sus pesos durante el entrenamiento para aprender patrones.';if(n.includes('como funciona'))return'Recibo una entrada, la paso por las capas, calculo una salida y ajusto los pesos mediante retropropagación.';if(n.includes('como estas'))return'Funcionando. Mis neuronas no duermen, una ventaja bastante sospechosa frente a los humanos. 😌';if(n.includes('que puedes hacer')||n.includes('ayuda'))return'Puedo entrenar XOR, guardar recuerdos, encontrar preguntas parecidas y aprender respuestas con «aprende: pregunta => respuesta».';if(n.includes('gracias'))return'De nada. 🧠';const remembered=findMemory(text);if(remembered)return`Recuerdo algo parecido: ${remembered.answer}`;if(n.endsWith('?'))return`Todavía no tengo una respuesta guardada para «${text}». Enséñamela con: aprende: ${text} => tu respuesta`;return`Recibí «${text}», pero todavía necesito conocimiento sobre ese tema.`}
function add(text,type){const el=document.createElement('div');el.className=type==='user'?'message userMessage':'message neuronMessage';el.textContent=text;$('messages')?.appendChild(el);if($('messages'))$('messages').scrollTop=$('messages').scrollHeight}
function pos(layer,index,w,h){const count=brain.layers[layer],x=30+(w-60)*layer/(brain.layers.length-1),gap=Math.min(46,(h-80)/Math.max(1,count-1));return{x,y:h/2+(index-(count-1)/2)*gap}}
function draw(){const c=$('networkCanvas');if(!c)return;const r=c.getBoundingClientRect(),w=Math.max(320,r.width||640),h=Math.max(320,r.height||420),d=Math.min(devicePixelRatio||1,2);c.width=w*d;c.height=h*d;const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.fillStyle='#090909';ctx.fillRect(0,0,w,h);const p=brain.layers.map((n,l)=>Array.from({length:n},(_,i)=>pos(l,i,w,h)));ctx.textAlign='center';ctx.font='10px system-ui';p.forEach((layer,l)=>{ctx.fillStyle='#777';ctx.fillText(l===0?'ENTRADA':l===p.length-1?'SALIDA':`OCULTA ${l}`,layer[0].x,18)});for(let l=0;l<p.length-1;l++)for(let a=0;a<p[l].length;a++)for(let b=0;b<p[l+1].length;b++){const wt=brain.weights[l][b][a];ctx.beginPath();ctx.moveTo(p[l][a].x,p[l][a].y);ctx.lineTo(p[l+1][b].x,p[l+1][b].y);ctx.lineWidth=Math.min(4,.7+Math.abs(wt)*2);ctx.strokeStyle=wt>=0?'rgba(220,220,220,.34)':'rgba(110,110,110,.30)';ctx.stroke()}p.forEach((layer,l)=>layer.forEach((v,i)=>{ctx.beginPath();ctx.arc(v.x,v.y,l===0||l===p.length-1?22:14,0,Math.PI*2);ctx.fillStyle='#202020';ctx.fill();ctx.lineWidth=2;ctx.strokeStyle='#888';ctx.stroke();ctx.fillStyle='#eee';ctx.font='600 9px system-ui';ctx.fillText(l===0?`x${i+1}`:l===p.length-1?'y':`h${l}.${i+1}`,v.x,v.y+3)}));ctx.fillStyle='#555';ctx.font='11px system-ui';ctx.fillText(trained?`Entrenada · época ${epoch.toLocaleString()} · ${learningEvents.toLocaleString()} experiencias`:'Lista para entrenar',w/2,h-12)}
function reset(){brain.reset();epoch=0;loss=1;trained=false;learningEvents=0;memory=[];saveLocal();update();if($('state'))$('state').textContent='Modelo reiniciado';queueSave()}
$('train')?.addEventListener('click',train);$('reset')?.addEventListener('click',reset);$('chatForm')?.addEventListener('submit',e=>{e.preventDefault();const input=$('chatInput'),q=input?.value.trim();if(!q)return;add(q,'user');input.value='';if(!trained){add('Primero entrena la red. 🧠','neuron');return}const a=answer(q);add(a,'neuron');saveMemory(q,a);learnInput(q);update()});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{$('chatInput').value=b.dataset.prompt||'';$('chatInput').focus()}));window.addEventListener('resize',draw);setStatus('cargando red…');update();load();
