-- Configuración segura de la memoria de RedNeuronal.
-- Puedes ejecutar este archivo varias veces sin errores.

create table if not exists public.neural_memory (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now()
);

alter table public.neural_memory enable row level security;

-- Elimina políticas anteriores para evitar errores 42710.
drop policy if exists "public can read neural memory" on public.neural_memory;
drop policy if exists "public can add neural memory" on public.neural_memory;
drop policy if exists "public can update neural memory" on public.neural_memory;

create policy "public can read neural memory"
on public.neural_memory for select to anon
using (true);

create policy "public can add neural memory"
on public.neural_memory for insert to anon
with check (char_length(question) between 1 and 300 and char_length(answer) between 1 and 600);

create policy "public can update neural memory"
on public.neural_memory for update to anon
using (true)
with check (char_length(question) between 1 and 300 and char_length(answer) between 1 and 600);

create index if not exists neural_memory_created_at_idx
on public.neural_memory (created_at desc);

-- Verificación: debe devolver la tabla y el número de filas.
select count(*) as recuerdos from public.neural_memory;
