-- Configuración segura de la memoria de RedNeuronal.
-- Puedes ejecutar este archivo varias veces sin errores.

create table if not exists public.iayo_memory (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now()
);

alter table public.iayo_memory enable row level security;

-- Elimina políticas anteriores para evitar errores 42710.
drop policy if exists "public can read neural memory" on public.iayo_memory;
drop policy if exists "public can add neural memory" on public.iayo_memory;
drop policy if exists "public can update neural memory" on public.iayo_memory;

create policy "public can read neural memory"
on public.iayo_memory for select to anon
using (true);

create policy "public can add neural memory"
on public.iayo_memory for insert to anon
with check (char_length(question) between 1 and 300 and char_length(answer) between 1 and 600);

create policy "public can update neural memory"
on public.iayo_memory for update to anon
using (true)
with check (char_length(question) between 1 and 300 and char_length(answer) between 1 and 600);

create index if not exists iayo_memory_created_at_idx
on public.iayo_memory (created_at desc);

-- Verificación: debe devolver la tabla y el número de filas.
select count(*) as recuerdos from public.iayo_memory;


-- Tablas nuevas de IAYO: conversaciones, mensajes y estado del modelo.
create table if not exists public.iayo_conversations (
  id uuid primary key default gen_random_uuid(),
  title text not null default 'Nueva conversación',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.iayo_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.iayo_conversations(id) on delete cascade,
  role text not null check (role in ('user','assistant','system')),
  content text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.iayo_model_state (
  id integer primary key default 1 check (id = 1),
  model_name text not null default 'IAYO',
  model_version text not null default '1.0.0',
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
