-- Ejecuta este SQL una sola vez en Supabase > SQL Editor.
-- Crea la memoria global que comparte el chat entre usuarios.

create table if not exists public.neural_memory (
  id bigint generated by default as identity primary key,
  question text not null check (char_length(question) between 1 and 300),
  answer text not null check (char_length(answer) between 1 and 600),
  created_at timestamptz not null default now()
);

alter table public.neural_memory enable row level security;

create policy "public can read neural memory"
on public.neural_memory
for select
to anon
using (true);

create policy "public can add neural memory"
on public.neural_memory
for insert
to anon
with check (
  char_length(question) between 1 and 300
  and char_length(answer) between 1 and 600
);

create policy "public can update neural memory"
on public.neural_memory
for update
to anon
using (true)
with check (
  char_length(question) between 1 and 300
  and char_length(answer) between 1 and 600
);

create index if not exists neural_memory_created_at_idx
on public.neural_memory (created_at desc);
